/**
 * PlantGuide SDK — TypeScript contracts
 *
 * These mirror the Python SDK in `src/plantguide/integrations/sdk.py`
 * (assess_for_app / care_for_app) so a Node/TS partner app can consume
 * `identify_response.schema.json` payloads directly.
 *
 * Every type mirrors the corresponding JSON schema under `schemas/`.
 * Treat the schemas as the source of truth — this file is generated by
 * `scripts/gen_ts_contracts.py` (or, in this PR, hand-written to match
 * the Python shapes byte-for-byte).
 */

// ----- Species ---------------------------------------------------------------

export interface SpeciesCare {
  summary: string;
  light: string;
  water: string;
  soil: string;
  humidity: string;
  /** Either a numeric range string like "18-27" or a single number. */
  temperature_c: string | number;
  fertilizer: string;
  toxicity: string;
  common_issues: string[];
  tips: string[];
}

export interface Species {
  id: string;             // snake_case
  common_name: string;
  scientific_name: string;
  tags: string[];
  care: SpeciesCare;
}

// ----- Observation (sample) -------------------------------------------------

export interface Observation {
  id: string;             // snake_case
  tags: string[];
  /** Optional: present on test fixtures for calibration. */
  expected_species?: string;
}

// ----- Care card (returned by care_for_app) ---------------------------------

export interface CareCard {
  species_id: string;
  common_name: string;
  scientific_name: string;
  summary: string;
  light: string;
  water: string;
  soil: string;
  humidity: string;
  temperature_c: string | number;
  fertilizer: string;
  toxicity: string;
  common_issues: string[];
  tips: string[];
}

// ----- Identify response ----------------------------------------------------

export interface IdentifyMatch {
  species_id: string;
  common_name: string;
  scientific_name?: string;
  /** [0, 1] */
  score: number;
  matched_tags?: string[];
}

export interface IdentifyResponse {
  matches: IdentifyMatch[];
  /** Convenience — present iff with_care=True and matches is non-empty. */
  top_care?: CareCard;
  /** Set by SDK assess_for_app() / care_for_app(). */
  integration_version?: string;
  /** Set by SDK assess_for_app(). */
  ready_for_ui?: boolean;
}

// ----- SDK contract (mirrors plantguide.integrations.sdk) ------------------

/** Mirrors `assess_for_app()` payload. */
export interface AssessResponse extends IdentifyResponse {
  integration_version: "plantguide.sdk.v1";
  ready_for_ui: true;
}

/** Mirrors `care_for_app()` payload. */
export interface CareForAppResponse extends CareCard {
  integration_version: "plantguide.sdk.v1";
}

// ----- Standalone helpers (no PlantGuide server required) ------------------

/**
 * Type guard: does this payload look like a Species?
 * Useful at app boundaries before passing to typed UI components.
 */
export function isSpecies(value: unknown): value is Species {
  if (!value || typeof value !== "object") return false;
  const v = value as Record<string, unknown>;
  return (
    typeof v.id === "string" &&
    typeof v.common_name === "string" &&
    typeof v.scientific_name === "string" &&
    Array.isArray(v.tags) &&
    typeof v.care === "object" &&
    v.care !== null
  );
}

/** Type guard: IdentifyResponse (matches always present). */
export function isIdentifyResponse(value: unknown): value is IdentifyResponse {
  if (!value || typeof value !== "object") return false;
  const v = value as Record<string, unknown>;
  return Array.isArray(v.matches);
}

/** Extract the top species id, or undefined if empty. */
export function topSpeciesId(r: IdentifyResponse): string | undefined {
  return r.matches[0]?.species_id;
}

/** Score for the top match, 0 if no matches. */
export function topScore(r: IdentifyResponse): number {
  return r.matches[0]?.score ?? 0;
}